/*
	LOGUEAR CLIENTE
*/


SELECT DNI,NOMBRE,APELLIDOPAT,APELLIDOMAT FROM CLIENTES WHERE DNI = '72417391' AND 
CLAVE = CRYPT('12345',CLAVE)


/*
	OBTENER LISTADO DE SERVICIOS
*/

SELECT IDSERVICIO,EMPRESA,TIPOEMPRESA FROM SERVICIOS WHERE EMPRESA ILIKE CONCAT('LUZ','%')