/*
	LOGUEAR CLIENTE
*/


SELECT DNI,NOMBRE,APELLIDOPAT,APELLIDOMAT FROM CLIENTES WHERE DNI = '72417391' AND 
CLAVE = CRYPT('12345',CLAVE)


/*
	OBTENER LISTADO DE SERVICIOS
*/


SELECT IDSERVICIO,TIPOEMPRESA FROM SERVICIOS WHERE TIPOEMPRESA ILIKE CONCAT('LUZ','%')

/*
	OBTENER LISTADO DE EMPRESAS
*/

SELECT IDSERVICIO,EMPRESA FROM SERVICIOS WHERE EMPRESA ILIKE CONCAT('SEDA','%');

/*
	GENERAR DEUDA ALEATORIA
	SELECT * FROM DEUDAS
*/

ALTER TABLE DEUDAS ADD COLUMN NROSUMINISTRO VARCHAR(6) -- EJECUTAR ESTA CONSULTA


INSERT INTO DEUDAS(IDCLIENTE,IDSERVICIO,MONTODEUDA,NROSUMINISTRO) 
VALUES (1,1,19.20,'BBVACOD');

/*
	LISTAR TARJETAS DEL CLIENTE
*/

SELECT SUBSTR(CODTARJETA,9) FROM PRODUCTOS WHERE IDCLIENTE = 1

/*
	REALIZAR PAGO DE SERVICIO
*/

INSERT INTO PAGOS(IDCLIENTE,IDPRODUCTO,IDSERVICIO,IDDEUDA,FECHA)
VALUES (1,2,1,3,NOW())
